
version = "1.0"
[main]

services = []

## WARNING : This file will be overwritten at installation and each app change.
## You shouldn't edit it, instead edit the conf/config_panel.toml.j2
    
[main.organization]
name = ""

[main.organization._name]
        ask.en = "Nom de l'oganisation"
        type = "string"
		bind = "organization.name>/var/www/__APP__/public/organization.properties"

