packaging_format = 2

id = "chatonsinfos"
name = "Chatons Infos"
description.en = "Create stats files Chatons compliant and enable configuration in config pannel"
description.fr = "Génère automatiquement les fichiers de statistiques Chatons et permet leur configuration dans le panneau de configuration"

version = "2023.12.21~ynh1"

maintainers = ["oiseauroch", "ljf"]

[upstream]
license = "AGPL-3.0"
demo = "https://stats.chatons.org/index.xhtml"
admindoc = "https://framagit.org/chatons/chatonsinfos/-/blob/master/README.md"
code = "https://framagit.org/chatons/chatonsinfos"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/.well_known/chatonsinfos/"
    
[resources]

    [resources.sources]
    
    [resources.sources.main]
    url = "https://framagit.org/chatons/chatonsinfos/-/archive/f55b95d91253150c8456d3b1330760fbc92b7e5c/chatonsinfos-f55b95d91253150c8456d3b1330760fbc92b7e5c.tar.bz2"
    sha256 = "80ed840c350d387ac419de66715158e5f01d9334f65fcdf5d632f5ab429dfb9e"
    format = "tar.gz"
    in_subdir = true
    autoupdate.strategy = "latest_gitlab_commit"
    
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.auth_header = false
