packaging_format = 2

id = "chatons_infos"
name = "Chatons Infos"
description.en = "create stats files Chatons compliant and enable configuration in config pannel"
description.fr = "génère automatiquement les fichiers de statistiques Chatons et permet leur configuration dans le panneau de configuration"

version = "1.0~ynh1"

maintainers = ["oiseauroch", "ljf"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "agpl-3.0"
website = "https://framagit.org/chatons/chatonsinfos/-/blob/master/"
demo = "https://stats.chatons.org/index.xhtml"
admindoc = "https://framagit.org/chatons/chatonsinfos/-/blob/master/README.md"
code = "https://framagit.org/chatons/chatonsinfos"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = "not_relevant"
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]
    
    [resourrces.sources.main]
    url = "https://framagit.org/chatons/chatonsinfos/-/archive/master/chatonsinfos-master.tar.gz?path=MODELES"
    sha256 = "664e1c934ea2fd0b5ee4ff55bbabbc81227a256ee12fd7d18319d13c095690bb"
    in_subdir = true
    
    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir
    dir = "/var/www/__APP__/"
