packaging_format = 2

id = "chatonsinfos"
name = "Chatons Infos"
description.en = "Create stats files Chatons compliant and enable configuration in config pannel"
description.fr = "Génère automatiquement les fichiers de statistiques Chatons et permet leur configuration dans le panneau de configuration"

version = "1.0~ynh1"

maintainers = ["oiseauroch", "ljf"]

[upstream]
license = "AGPL-3.0"
demo = "https://stats.chatons.org/index.xhtml"
admindoc = "https://framagit.org/chatons/chatonsinfos/-/blob/master/README.md"
code = "https://framagit.org/chatons/chatonsinfos"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/.well_known/chatonsinfos/"
    
[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]
    
    [resources.sources.main]
    url = "https://framagit.org/chatons/chatonsinfos/-/archive/master/chatonsinfos-master.tar.gz?path=MODELES"
    sha256 = "664e1c934ea2fd0b5ee4ff55bbabbc81227a256ee12fd7d18319d13c095690bb"
    format = "tar.gz"
    in_subdir = true
    
    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.auth_header = false
