#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=host_server_distribution --value="YunoHost"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/sources"

mkdir $install_dir/public

# Empty html page to fix the CI
echo "<html><body>ChatonsInfos</body></html>" > $install_dir/public/index.html
# $install_dir will automatically be initialized with some decent

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

cp "$install_dir/sources/MODELES/organization.properties" "$install_dir/public/"
orga_path="$install_dir/public/organization.properties"

ynh_write_var_in_file --file="$orga_path" --key="file.datetime" --value="$(date '+%Y-%m-%dT%H:%M:%S')"
ynh_write_var_in_file --file="$orga_path" --key="file.generator" --value="chatonsinfos_ynh"

chown -R $app:www-data "$install_dir/public"

#=================================================
# GENERATE CONFIG PANEL
#=================================================
ynh_script_progression "Generating configuration panel..."

generate_config_panel

#=================================================
# ADD A CRON JOB
#=================================================
ynh_script_progression "Adding cron job to generate metrics..."

ynh_config_add --template="cron" --destination="/etc/cron.daily/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
