#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/sources"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# GENERATE CONFIG PANEL
#=================================================
ynh_script_progression "Generating configuration panel..."

generate_config_panel

chmod 400 "$install_dir/public/organization.properties"
chown $app:www-data "$install_dir/public/organization.properties"

ynh_store_file_checksum "$install_dir/public/organization.properties"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
